baseURL: "https://hugo-theme-shoka.birdgg.me/"
languageCode: "en-us"
defaultContentLanguage: zh-cn
title: "Birdgg's blog"
theme: "hugo-theme-shoka"

author:
  name: birdgg

enableEmoji: true

hasCJKLanguage: true
summaryLength: 50

paginate: 8
taxonomies:
  tag: tags
  series: series


permalinks:
  posts: /:slug

pygmentsUseClasses: true
markup:
  highlight:
    style: ''
    guessSyntax: true
    lineNumbersInTable: true
    lineNos: true
    codeFences: true
  goldmark:
    renderer:
      unsafe: true # enable html in markdown

menu:
  main:
  - identifier: home
    name: Home
    params: 
      icon: ic i-home
    weight: 10
    url: /
  - identifier: archives
    name: Archives
    params: 
      icon: ic i-feather
    weight: 40
    url: /archives/

outputs:
  home: ["HTML", "RSS", "JSON", "Algolia"]

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true

params:
  alternate: 'Birdgg'
  subtitle: "subtitle"
  author: "birdgg"
  description: this is description
  avatar: avatar.jpg
  since: 2022

  widgets:
    random_posts: true
    recent_comments: true

  algolia:
    appid: EKZ0OK6SKN
    apikey: c4880b6c9b50843998e94547ea3476f4
    indexname: dev_blog
    hits: 10
