baseURL: "https://birdgg.github.io/hugo-theme-shoka/"
languageCode: "en-us"
defaultContentLanguage: zh-cn
title: "Birdgg's blog"
theme: "hugo-theme-shoka"

enableEmoji: true

hasCJKLanguage: true
summaryLength: 50

paginate: 8
taxonomies:
  tag: tags
  series: series


permalinks:
  posts: /:slug

pygmentsUseClasses: true
markup:
  highlight:
    style: ''
    guessSyntax: true
    lineNumbersInTable: true
    lineNos: true
    codeFences: true
  goldmark:
    renderer:
      unsafe: true # enable html in markdown

menu:
  main:
  - identifier: home
    name: Home
    params: 
      icon: ic i-home
    weight: 10
    url: /
  - identifier: archives
    name: Archives
    params: 
      icon: ic i-feather
    weight: 40
    url: /archives/
