baseURL: "https://hugo-theme-shoka.birdgg.me/"
languageCode: "en-us"
defaultContentLanguage: zh-cn
title: "Birdgg's blog"
theme: "hugo-theme-shoka"

author:
  name: birdgg

enableEmoji: true

hasCJKLanguage: true
summaryLength: 50

paginate: 8
taxonomies:
  tag: tags
  series: series


permalinks:
  posts: /:slug

pygmentsUseClasses: true
markup:
  highlight:
    style: ''
    guessSyntax: true
    lineNumbersInTable: true
    lineNos: true
    codeFences: true
  goldmark:
    renderer:
      unsafe: true # enable html in markdown

menu:
  main:
  - identifier: home
    name: Home
    params: 
      icon: ic i-home
    weight: 10
    url: /
  - identifier: archives
    name: Archives
    params: 
      icon: ic i-feather
    weight: 40
    url: /archives/

outputs:
  home: ["HTML", "RSS", "JSON", "Algolia"]

outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true

params:
  alternate: 'Birdgg'
  subtitle: "subtitle"
  description: this is description
  statics: /
  avatar: avatar.jpg
  since: 2022

  sidebar:
    avatar: avatar.jpg
    position: right

  fancybox: true

  widgets:
    random_posts: true
    recent_comments: true

  reward:
    enable: true
    account:
      wechatpay: wechatpay.jpg
      alipay: alipay.png

  algolia:
    appid: EKZ0OK6SKN
    apikey: c4880b6c9b50843998e94547ea3476f4
    indexname: dev_blog
    hits: 10

  valine:
    appId: IkYoEMgcMR92dFG5RGmdTL6o-gzGzoHsz
    appKey: uBaPTuHf0aUkmnVYSP1SMpp7
    placeholder: ヽ(○´∀`)ﾉ♪
    avatar: mp
    pageSize: 10
    lang: zh-CN
    visitor: true
    NoRecordIP: false
    serverURLs:
    powerMode: true
    tagMeta:
      visitor: 新朋友
      master: 主人
      friend: 小伙伴
      investor: 金主粑粑
    tagColor:
      master: "var(--color-orange)"
      friend: "var(--color-aqua)"
      investor: "var(--color-pink)"
    tagMember:
      master:
      friend:
      investor:
